import "./globals.css";

import { CartProvider } from "@/context/cartContext"; // Adjust the path if necessary
import CartSidebar from "@/components/cart/CartSidebar";
import { Inter as FontSans } from "next/font/google";
import Header from "@/components/site-header";
import MainHeader from "@/components/layouts/MainHeader";
import type { Metadata } from "next";
import { Providers } from "@/components/Providers";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Shop@Us",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers>
          <Toaster />
          <CartProvider>
            <ReactQueryProvider>
              {/* Pass the cart context values as props */}
              <MainHeader/>
              {children}
            </ReactQueryProvider>
            <CartSidebar />
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}



